arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: true
jsxSingleQuote: true
printWidth: 100
quoteProps: as-needed
semi: false
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
